### ISSUE TITLE
missing test.ts

### ISSUE THREAD

**Issue by mbjelac** [ahnpnl/jest-angular#1]
`tsconfig.spec.json` references `test.ts` in the `files` section, but there is no such file in the repo.

This causes jest to break:

```
$ jest
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    error TS6053: File '.../jest-angular/src/test.ts' not found.

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.219s
Ran all test suites.
```

When I remove the reference (and clear jest cache), everything works again.

**Comment by ahnpnl** [comment]
fixed for [tsconfig.app.json](https://github.com/ahnpnl/jest-angular/commit/aab13706a45e0d1f978e8541376090ddd8622e55) and [tsconfig.spec.json](https://github.com/ahnpnl/jest-angular/commit/591238e8fe2fbb31f8f510bd28c063040fc8ee5e)
